#!/bin/bash
repo=$(dirname $0)

echo "Pulling changes from github.."
git pull origin master > /dev/null

echo "Copying configs to $HOME/.config folder"
for i in $(ls $repo/configs)
do
    cp -r $repo/configs/$i $HOME/.config > /dev/null
done

echo "Copying bins to /bin folder"
for i in $(ls $repo/bin)
do
    sudo cp $repo/bin/$i /bin > /dev/null
done

echo "Update completed!"
