#!/bin/bash
sudo -k
echo "Verify to begin the UPDATE"
sudo echo "Verified." || { echo "You must verify"; exit 1; }

repo=$(dirname $0)
cfgs=$(cat $repo/lists/configs)
cfgs_rel=$(cat $repo/lists/configs_rel)
bins=$(cat $repo/lists/bin)
dev_rel=$repo/$(cat $repo/.device)_relative

echo "Pulling changes from github.."
git pull origin master > /dev/null

echo "Copying .zshrc to $HOME folder.."
if ! $(diff -qr $HOME/.zshrc $repo/.zshrc); then
    rm $HOME/.zshrc
    cp $repo/.zshrc $HOME
fi

echo "Copying configs to $HOME/.config folder.."
for i in $cfgs
do
    if ! $(diff -qr $HOME/.config/$i $repo/configs/$i); then
        rm -rf $HOME/.config/$i
        cp -r $repo/configs/$i $HOME/.config > /dev/null
    fi
done

echo "Copying relative configs to $HOME/.config folder.."
for i in $cfgs_rel
do
    if ! $(diff -qr $HOME/.config/$i $dev_rel/$i); then
        rm -rf $HOME/.config/$i
        cp -r $dev_rel/$i $HOME/.config/$i > /dev/null
    fi
done

echo "Copying bins to /bin folder.."
for i in $bins
do
    if ! $(sudo diff -qr /bin/$i $repo/bin/$i); then
        sudo rm -rf /bin/$i
        sudo cp $repo/bin/$i /bin > /dev/null
        sudo chmod +x /bin/$i > /dev/null
    fi
done

hyprctl reload
echo "Update completed!"
