#!/bin/bash
. ./vars          || exit 1
. ./verify UPLOAD || exit 1

if ! $(diff -qr $repo/.zshrc $HOME/.zshrc); then
    printf "$info Uploading new .zshrc.."
    rm $repo/.zshrc
    cp $HOME/.zshrc $repo
    printf "$ers$ok Uploaded new .zshrc\n"
fi

for i in $cfgs
do
    if ! $(diff -qr $repo/configs/$i $HOME/.config/$i); then
        printf "$info Uploading new $i User config.."
        rm -rf $repo/configs/$i
        cp -r $HOME/.config/$i $repo/configs/$i > /dev/null
        printf "$ers$ok Uploaded new $i User config\n"
    fi
done

for i in $cfgs_rel
do
    if ! $(diff -qr $dev_rel/$i $HOME/.config/$i); then
        printf "$info Uploading new $i User config.."
        rm -rf $dev_rel/$i
        if [[ $i == */* ]]; then
            mkdir $dev_rel/$(dirname $i) 2>/dev/null
            rm -rf $repo/configs/$i
        fi
        cp -r $HOME/.config/$i $dev_rel/$i > /dev/null
        printf "$ers$ok Uploaded new $i User config\n"
    fi
done

for i in $etcs
do
    if ! $(sudo diff -qr $repo/etc/$i /etc/$i); then
        printf "$info Uploading new $i System config\n"
        sudo rm -rf $repo/etc/$i
        sudo cp -r /etc/$i $repo/etc/$i
    fi
done

for i in $bins
do
    if ! $(sudo diff -qr $repo/bin/$i /bin/$i); then
        printf "$info Uploading new $i Executable.."
        sudo rm -rf $repo/bin/$i
        cp /bin/$i $repo/bin/$i > /dev/null
        printf "$ers$ok Uploaded new $i Executable\n"
    fi
done

git add $repo
git commit -m "update" > /dev/null

printf "$info Pushing changes to github.."
git push origin master > /dev/null && printf "$ers$ok Pushed changes to github" || (printf "$ers$warning Failed to push changes to github")

printf "$ok Uploading completed\n"
