#!/bin/bash
. ./vars          || exit 1
. ./verify UPLOAD || exit 1

for i in $homes
do
    if ! $(diff -qr ./home/$i $HOME/$i >/dev/null 2>/dev/null); then
        printf "$info Uploading new $i home file.."
        rm ./home/$i 2>/dev/null
        cp $HOME/$i ./home/$i
        printf "$ers$ok Uploaded new $i home file\n"
    fi
done

for i in $cfgs
do
    if ! $(diff -qr ./configs/$i $HOME/.config/$i >/dev/null 2>/dev/null); then
        printf "$info Uploading new $i User config.."
        rm -rf ./configs/$i 2>/dev/null
        cp -r $HOME/.config/$i ./configs/$i > /dev/null
        printf "$ers$ok Uploaded new $i User config\n"
    fi
done

for i in $cfgs_rel
do
    if ! $(diff -qr $dev_rel/$i $HOME/.config/$i >/dev/null 2>/dev/null); then
        printf "$info Uploading new $i User config.."
        rm -rf $dev_rel/$i 2>/dev/null
        if [[ $i == */* ]]; then
            mkdir $dev_rel/$(dirname $i) 2>/dev/null
            rm -rf ./configs/$i 2>/dev/null
        fi
        cp -r $HOME/.config/$i $dev_rel/$i > /dev/null
        printf "$ers$ok Uploaded new $i User config\n"
    fi
done

for i in $etcs
do
    if ! $(sudo diff -qr ./etc/$i /etc/$i >/dev/null 2>/dev/null); then
        printf "$info Uploading new $i System config\n"
        sudo rm -rf ./etc/$i 2>/dev/null
        sudo cp -r /etc/$i ./etc/$i
    fi
done

for i in $bins
do
    if ! $(sudo diff -qr ./bin/$i /bin/$i >/dev/null 2>/dev/null); then
        printf "$info Uploading new $i Executable.."
        sudo rm -rf ./bin/$i 2>/dev/null
        cp /bin/$i ./bin/$i > /dev/null
        printf "$ers$ok Uploaded new $i Executable\n"
    fi
done

git add .
git commit -m "update" > /dev/null

printf "$info Pushing changes to github.."
git push origin master > /dev/null 2>/dev/null && printf "$ers$ok Pushed changes to github\n" || (printf "$ers$warning Failed to push changes to github\n")

printf "$ok Uploading completed\n"
