#!/bin/bash
info="[\e[0;35mINFO\e[0m]"
prmpt="[\e[0;96mPROMPT\e[0m]"
warning="[\e[0;93mWARNING\e[0m]"
error="[\e[0;91mERROR\e[0m]"
ok="[\e[0;92mOK\e[0m]"

ers="\e[0G\e[K"

homes=$(cat ./lists/home)
cfgs=$(cat ./lists/configs)
cfgs_rel=$(cat ./lists/configs_rel)
etcs=$(cat ./lists/etc)
bins=$(cat ./lists/bin)
