#!/bin/bash
. vars
sudo -k
printf "$prmpt Verify to begin the \e[1m$1\e[0m\n"
sudo printf "$ok Verified.\n" || { printf "$error You must verify\n"; exit 1; }

printf "$info Getting device info.."
if [[ -f .device ]]; then
    device=$(cat .device)
else
    printf "\n$prmpt What's your device? "
    read device
    echo $device > .device
    mkdir "$device"_relative 2>/dev/null
fi    
dev_rel="$device"_relative
printf "$ers$ok Got device info\n"
