#!/bin/bash
repo=$HOME/.dotfiles/
cfgs=$(cat $repo/configlist)

echo "Copying configs to local repo.."
for i in $cfgs
do
    cp -r $HOME/.config/$i $repo/configs
done

echo "Adding and commiting changes.."
git add $repo
git commit -m "update"

echo "Pushing changes to github.."
git push origin master

echo "Uploading completed"
